#!/bin/sh

# Submit to the rascals queue
#$ -q *@@rascals.h

# Name of the job
#$ -N keep-unique-reads

# Execute the script from the current directory
#$ -cwd

# Combine SGE error and output files.
#$ -j y

# Memory resource requirements
#$ -l h_vmem=4g

# Number of threads/cpus
#$ -pe smp 1

cd ${TMP}/
$GOBY 3g tally-reads -i ${DATA_DIR}/${BASENAME}.compact-reads -o ${DATA_DIR}/${BASENAME}.uniqset

