#!/bin/sh  

# This script runs Goby with the specified amount of memory.
# The script will find the Goby jar if it is located in the same directory as this script

# Usage: goby mem-requirement mode-name [param]+
# Where mem-requirement indicates how much memory Goby should be given (e.g., 1g, 500m).
# Mode-name should specify a Goby mode.
# For instance, the following command will display the Goby version number:

#     goby 40m version
 
export memory_requirement=$1
shift
export other_parameters=$*


export WORKING_DIR=`dirname "$0"`
export GOBY_JAR=${WORKING_DIR}/../../goby.jar

echo java -Xmx${memory_requirement} -jar ${GOBY_JAR} --mode ${other_parameters}
java -Xmx${memory_requirement} -jar ${GOBY_JAR} --mode ${other_parameters}