#!/bin/sh  

# This script runs Goby with the specified amount of memory.
# The script will find the Goby jar if it is located in the same directory as this script

# Usage: goby mem-requirement mode-name [param]+
# Where mem-requirement indicates how much memory Goby should be given (e.g., 1g, 500m).
# Mode-name should specify a Goby mode.
# For instance, the following command will display the Goby version number:

#     goby 40m version
 
export memory_requirement=$1
shift
export other_parameters=$*


export WORKING_DIR=`dirname "$0"`
export GOBY_JAR=${WORKING_DIR}/goby.jar
export GOBY_HOME=${WORKING_DIR}
      
if [ "${RJAVA_HOME:-notset}" == "notset" ]; then
  echo "Trying to set RJAVA_HOME environment variable"
  cat >/tmp/r-cmd.txt <<EOT
system.file("jri",package="rJava")
EOT
  export RJAVA_HOME=`R --no-save </tmp/r-cmd.txt|grep [1]|tail -1 |awk '{print $2}'`
  rm -f /tmp/r-cmd.txt
 
fi

echo java -ea -Xmx${memory_requirement} -Djava.library.path=${RJAVA_HOME} -jar ${GOBY_JAR} --mode ${other_parameters}
java -ea -Xmx${memory_requirement} -Dlog4j.configuration=file://${GOBY_HOME}/config/log4j-sample.properties -Djava.library.path=${RJAVA_HOME} -jar ${GOBY_JAR} --mode ${other_parameters}
