#!/bin/sh

# Submit to the rascals queue
#$ -q *@@rascals.h

# Name of the job
#$ -N bz2compact

# Execute the script from the current directory
#$ -cwd

# Combine SGE error and output files.
#$ -j y

# Memory resource requirements
#$ -l h_vmem=2g

# Number of threads/cpus
#$ -pe smp 2


cd $TMP
bzcat -f ${DATA_DIR}/${BASENAME}.fastq.bz2 >${BASENAME}.fastq
$GOBY 1g fasta-to-compact ${BASENAME}.fastq
cp ${BASENAME}.compact-reads ${SGE_O_WORKDIR}/



